name: Auto Merge

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' || contains(github.head_ref, 'auto-merge')
    steps:
    - name: Check PR status
      id: pr-status
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pr } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
          });

          // Check if CI is successful
          const { data: checks } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: pr.head.sha,
          });

          const allPassed = checks.check_runs.every(check =>
            check.status === 'completed' && check.conclusion === 'success'
          );

          console.log('All checks passed:', allPassed);
          return allPassed;

    - name: Auto approve and merge
      if: steps.pr-status.outputs.result == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const pr_number = context.issue.number;

          // Auto approve
          await github.rest.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
            event: 'APPROVE',
            body: '🤖 Auto-approved by CI workflow'
          });

          // Auto merge
          await github.rest.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pr_number,
            merge_method: 'squash',
            commit_title: '🤖 Auto-merge: ' + context.payload.pull_request.title,
            commit_message: 'Automatically merged after successful CI checks'
          });

          console.log('PR auto-merged successfully');
